### ISSUE TITLE
Is the pretrained model available?

### ISSUE THREAD

**Issue by shahhaard47** [utahnlp/therapist-observer#1]
Hello, I am working with counseling dataset and would like to label utterances with MI codes using your model. It would be really helpful if you could provide your trained model. 

Look forward to hearing from you. 

Thank you!

**Comment by mlciv** [comment]
Sorry for the late response. Thanks for your interest for our work. 
Because our model are trained on a protected dataset, we cannot provide the pretrained model.
However, with your own dataset, I suggested that you can simply train a model from a pretrained BERT. 
Recently, we also explored transformer-based model on MI code  predictions, it shows better performance.  I hope the following code and thesis will help. 

Code: https://github.com/utahnlp/bert-therapy/
Paper: https://www.cs.utah.edu/docs/techreports/2020/pdf/UUCS-20-011.pdf

**Comment by shahhaard47** [comment]
Thanks for the response! I'm trying to understand therapist behaviors in my dataset roughly without having to label MI codes haha. I understand this kind of data is protected, do you think there are any implementations that are able to share a similar MI code classifier or a labeled dataset with MI codes? 

Any guidance is appreciated!

**Comment by mlciv** [comment]
I don't know any public resource like this.  
I know there is a company that you can try their service by uploading your session.  
Maybe you can have a try. 
https://www.lyssn.io/support
